# Generated by Django 4.2.7 on 2025-05-12 15:51

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('plain_password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('curriculumSubjectId', models.AutoField(primary_key=True, serialize=False)),
                ('subjectCode', models.CharField(max_length=50, unique=True)),
                ('subjectName', models.CharField(max_length=255)),
                ('theoreticalCredits', models.IntegerField()),
                ('practiceCredit', models.IntegerField()),
                ('max_students', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentCode', models.CharField(max_length=50, unique=True)),
                ('departmentName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('adminCode', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.customuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('studentCode', models.CharField(max_length=50, unique=True)),
                ('fullName', models.CharField(max_length=255)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=app.models.student_profile_picture_path)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('className', models.CharField(blank=True, max_length=50, null=True)),
                ('k', models.IntegerField(blank=True, null=True)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_students', to='app.department')),
            ],
            bases=('app.customuser',),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Mở', 'Mở'), ('Đóng', 'Đóng'), ('Chấp Nhận Mở Lớp', 'Chấp Nhận Mở Lớp')], default='Mở', max_length=50)),
                ('max_students', models.IntegerField(default=30)),
                ('current_students', models.IntegerField(default=0)),
                ('curriculum_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_subjects', to='app.curriculumsubject')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('majorId', models.AutoField(primary_key=True, serialize=False)),
                ('majorCode', models.CharField(max_length=50, unique=True)),
                ('majorName', models.CharField(max_length=255)),
                ('total_semesters', models.IntegerField(default=8)),
                ('theoretical_credit_price', models.FloatField(default=0.0, help_text='Giá mỗi tín chỉ lý thuyết')),
                ('practical_credit_price', models.FloatField(default=0.0, help_text='Giá mỗi tín chỉ thực hành')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_majors', to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturerCode', models.CharField(max_length=50, unique=True)),
                ('lecturerName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_lecturers', to='app.department')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_lecturers', to='app.major')),
            ],
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_curriculum_subjects', to='app.department'),
        ),
        migrations.CreateModel(
            name='CurriculumFramework',
            fields=[
                ('curriculumFrameworkId', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('is_mandatory', models.BooleanField(default=False)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_curriculums', to='app.major')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_curriculums', to='app.curriculumsubject')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classId', models.AutoField(primary_key=True, serialize=False)),
                ('classCode', models.CharField(max_length=50, unique=True)),
                ('className', models.CharField(max_length=255)),
                ('is_nominal', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_classes', to='app.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_classes', to='app.lecturer')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_classes', to='app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('studentClassId', models.AutoField(primary_key=True, serialize=False)),
                ('registerDate', models.DateField(blank=True, null=True)),
                ('semester', models.IntegerField()),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_registrations', to='app.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='app.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='app.major'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('staffId', models.AutoField(primary_key=True, serialize=False)),
                ('staffCode', models.CharField(max_length=50, unique=True)),
                ('staffName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=app.models.staff_profile_picture_path)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_staffs', to='app.department')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_staffs', to='app.major')),
                ('managed_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing_staffs', to='app.student')),
            ],
            bases=('app.customuser',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('paymentCode', models.CharField(max_length=50, unique=True)),
                ('amount', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_payments', to='app.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='app.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_student_email'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_staff_email'),
        ),
    ]
