# Generated by Django 5.0.3 on 2025-03-12 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('plain_password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentCode', models.CharField(max_length=50, unique=True)),
                ('departmentName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('adminCode', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.customuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('studentCode', models.CharField(max_length=50, unique=True)),
                ('fullName', models.CharField(max_length=255)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('className', models.CharField(blank=True, max_length=50, null=True)),
                ('k', models.IntegerField(blank=True, null=True)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, default='IMG/default_avatar.png', null=True, upload_to='profile_pics/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.department')),
            ],
            bases=('app.customuser',),
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('majorId', models.AutoField(primary_key=True, serialize=False)),
                ('majorCode', models.CharField(max_length=50, unique=True)),
                ('majorName', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
                ('subjectCode', models.CharField(max_length=50, unique=True)),
                ('subjectName', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('theoreticalCredits', models.IntegerField()),
                ('practiceCredit', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturerId', models.AutoField(primary_key=True, serialize=False)),
                ('lecturerCode', models.CharField(max_length=50, unique=True)),
                ('lecturerName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='app.department')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='app.major')),
                ('subjects', models.ManyToManyField(blank=True, related_name='lecturers', to='app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumFramework',
            fields=[
                ('curriculumFrameworkId', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='app.major')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('staffId', models.AutoField(primary_key=True, serialize=False)),
                ('staffCode', models.CharField(max_length=50, unique=True)),
                ('staffName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, default='IMG/default_avatar.png', null=True, upload_to='profile_pics/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='app.department')),
            ],
            bases=('app.customuser',),
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('studentClassId', models.AutoField(primary_key=True, serialize=False)),
                ('registerDate', models.DateField(blank=True, null=True)),
                ('semester', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.major'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('paymentCode', models.CharField(max_length=50, unique=True)),
                ('amount', models.FloatField()),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_staff_email'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_student_email'),
        ),
    ]
