# Generated by Django 5.0.3 on 2025-03-02 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('staffId', models.AutoField(primary_key=True, serialize=False)),
                ('staffCode', models.CharField(max_length=50, unique=True)),
                ('staffName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('departmentId', models.IntegerField(blank=True, null=True)),
                ('is_email_sent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.customuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('studentCode', models.CharField(max_length=50, unique=True)),
                ('fullName', models.CharField(max_length=255)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('className', models.CharField(blank=True, max_length=50, null=True)),
                ('k', models.IntegerField(blank=True, null=True)),
                ('majorId', models.IntegerField(blank=True, null=True)),
                ('departmentId', models.IntegerField(blank=True, null=True)),
                ('is_email_sent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.customuser',),
        ),
    ]
