# Generated by Django 4.2.7 on 2025-05-25 07:20

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='elective_credits_per_semester',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='major',
            name='required_credits_per_semester',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='major',
            name='practical_credit_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='major',
            name='theoretical_credit_price',
            field=models.FloatField(default=0.0),
        ),
    ]
