# Generated by Django 4.2.7 on 2025-05-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_major_elective_credits_per_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='elective_credits_per_semester',
        ),
        migrations.RemoveField(
            model_name='major',
            name='required_credits_per_semester',
        ),
        migrations.AddField(
            model_name='major',
            name='credits_per_semester',
            field=models.JSONField(default=dict, help_text='Số tín chỉ bắt buộc và tự chọn mỗi kỳ'),
        ),
        migrations.AlterField(
            model_name='major',
            name='practical_credit_price',
            field=models.FloatField(default=0.0, help_text='Giá mỗi tín chỉ thực hành'),
        ),
        migrations.AlterField(
            model_name='major',
            name='theoretical_credit_price',
            field=models.FloatField(default=0.0, help_text='Giá mỗi tín chỉ lý thuyết'),
        ),
    ]
